---
- hosts: webservers
  gather_facts: no
  become: yes
  become_user: nagios
  
  tasks:
    - name: Run check
      command: /usr/local/nagios/bin/nagios -v /usr/local/nagios/etc/nagios.cfg
      register: output

    - debug:
        var: output.stdout_lines

